server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        proxy_pass http://backend:8000/health;
    }

    location = /models {
        proxy_pass http://backend:8000/models;
    }

    location = /predict/image {
        proxy_pass http://backend:8000/predict/image;
    }

    location = /docs {
        proxy_pass http://backend:8000/docs;
    }

    location = /redoc {
        proxy_pass http://backend:8000/redoc;
    }

    location = /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
    }

    location = /docs/oauth2-redirect {
        proxy_pass http://backend:8000/docs/oauth2-redirect;
    }
}
